function lattice = stream_lattice(lattice)

    % 1
    lattice_distribution = lattice{1};
    size_lattice = size(lattice_distribution(:, :, 1));
    number_lines_lattice = size_lattice(1);
    number_columns_lattice = size_lattice(2);

    % 2
    lattice_distribution(:,:,1) = [lattice_distribution(:,1:2,1) ...
    lattice_distribution(:,2:number_columns_lattice-1,1)];
    lattice_distribution(:,:,2) = [lattice_distribution(1:2,:,2); ...
    lattice_distribution(2:number_lines_lattice-1,:,2)];
    lattice_distribution(:,:,3) = [lattice_distribution(:,2:number_columns_lattice-1,3) ...
    lattice_distribution(:,number_columns_lattice-1:number_columns_lattice,3)];
    lattice_distribution(:,:,4) = [lattice_distribution(2:number_lines_lattice-1,:,4); ... 
    lattice_distribution(number_lines_lattice-1:number_lines_lattice,:,4)];
    lattice_distribution(:,:,5) = [lattice_distribution(:,1:2,5) ...
    lattice_distribution(:,2:number_columns_lattice-1,5)];
    lattice_distribution(:,:,5) = [lattice_distribution(1:2,:,5); ... 
    lattice_distribution(2:number_lines_lattice-1,:,5)];
    lattice_distribution(:,:,6) = [lattice_distribution(:,2:number_columns_lattice-1,6) ...
    lattice_distribution(:,number_columns_lattice-1:number_columns_lattice,6)];
    lattice_distribution(:,:,6) = [lattice_distribution(1:2,:,6); ... 
    lattice_distribution(2:number_lines_lattice-1,:,6)];
    lattice_distribution(:,:,7) = [lattice_distribution(:,2:number_columns_lattice-1,7) ...
    lattice_distribution(:,number_columns_lattice-1:number_columns_lattice,7)];
    lattice_distribution(:,:,7) = [lattice_distribution(2:number_lines_lattice-1,:,7); ... 
    lattice_distribution(number_lines_lattice-1:number_lines_lattice,:,7)];
    lattice_distribution(:,:,8) = [lattice_distribution(:,1:2,8) ...
    lattice_distribution(:,2:number_columns_lattice-1,8)];
    lattice_distribution(:,:,8) = [lattice_distribution(2:number_lines_lattice-1,:,8); ... 
    lattice_distribution(number_lines_lattice-1:number_lines_lattice,:,8)];

    %% 4
    lattice{1} = lattice_distribution;