function[]=export_vtk(mesh,filename)


%% Create file

vtkfilename = strcat([num2str(c(1)),'_',num2str(c(2)),'_',num2str(c(3)),'_',filename,'_completemesh.vtk']);

fid = fopen(vtkfilename,'w');

%% Header
% lines: 5
% The first line simply describes the version number. The second line can contain what ever you want, for example a bit of information about who generated the file. The third simply determines the filetype: ASCII. The forth describes what kind of data VTK can expected in the rest of the file. There are five different types: Three structured types (STRUCTURED_POINTS, STRUCTURED_GRID, RECTILINEAR_GRID) in which all points somehow lineup or match, not very usable. One surface type (POLYDATA) which doesn't contain volume, not what we need. And finally UNSTRUCTURED_GRID which describes arbitrary combinations of all availible cells types. This is what we like.
% The fifth line is empty.
% --> Unstructured grid: 2D or 3D grid; for every grid point all three coordinates and for each grid cell all constituent points and the cell shape are given. XML file extension: *.vtu
% --> Polygonal data:    2D grid; like the unstructured grid, but there are no polyhedra, but only flat polygons. Especially suited for maps (topography). XML file extension: *.vtp
% --> Rectilinear grid:  3D grid; the grid cells are cuboids, so only the steps along the coordinate axes have to be given, but not the individual point coordinates or the connectivity.
% --> Structured grid:   3D grid; here, all point coordinates are given, but the connectivity is omitted.
% --> Structured points: Like the rectilinear grid, but the spacing between the points is equidistant; so only the origin and the spacing has to be given, not the point coordinates.


c = clock;
fprintf(fid,'# vtk DataFile Version 6.0\n');
fprintf(fid,strcat(['Mesh generated by Luca Di Stasio, Computational Physics of Engineering Materials, Institute for Building Materials, ETH Zuerich on ',num2str(c(3)),'-',num2str(c(2)),'-',num2str(c(1)),'\n']));
fprintf(fid,'ASCII\n');
fprintf(fid,'DATASET UNSTRUCTURED_GRID');
fprintf(fid,' \n');

%% Pointdata
% lines: #nr_points+2
% The first line notes how many points there will be ("9") and in which format they'll be supplied (usually "FLOAT"). Nine lines follow, each line containing the xyz-coordinates of a point.
% Based on this list, each point is assigned an id. The first point has id 0, the second point id 1, and so forth, till the last point with id 8.
% The last line is empty.

fprintf(fid,'POINTS %d FLOAT\n',mesh.totN);
for i=1:mesh.totN
    fprintf(fid,'%12.8f %12.8f %12.8f\n',mesh.nodes.meshcoordinates(1,i),mesh.nodes.meshcoordinates(2,i),mesh.nodes.meshcoordinates(3,i));
end
fprintf(fid,' \n');

%% Celldata
% lines: #nr_cells+5
% The first line notes how many cells there will be ("4") and how many numbers total will be supplied in the CELLS-block ("20"). Four lines follow, each line containing the information for a cell.
% Each cell line starts with a number saying how many point-ids are to be read in that line followed by the list of those point-ids.
% Based on this list, each cell is assigned an id. The first cell has id 0, the second id 1, and so forth, till the last cell with id 3.
% After all cells have been given points, the cell types have to be set.
% This is done in the CELL_TYPES-block.
% The CELL_TYPES-line says how many cell-types are to be set. This number has to be the same as the number in the CELLS-line ("4"). The following line is a list of cell-types that are assigned to all cells. The first cell is of type "9", so ist the second cell and so forth.
% The last line is empty.

switch mesh.D
    case 1
        if mesh.edgeflag
            fprintf(fid,'CELLS %d %d\n',mesh.totE,mesh.totE*3);
            for i=1:mesh.totE
                fprintf(fid,'2 %d %d\n',mesh.edges.nodes(1,i)-1,mesh.edges.nodes(2,i)-1);
            end
            fprintf(fid,'CELL_TYPES %d\n',mesh.totE);
            for i=1:mesh.totE
                fprintf(fid,'3\n');
            end
            fprintf(fid,' \n')
        end
    case 2
        if mesh.faceflag
            fprintf(fid,'CELLS %d %d\n',mesh.totF,mesh.totF*5);
            for i=1:mesh.totF
                fprintf(fid,'4 %d %d %d %d\n',mesh.faces.nodes(1,i)-1,mesh.faces.nodes(2,i)-1,mesh.faces.nodes(3,i)-1,mesh.faces.nodes(4,i)-1);
            end
            fprintf(fid,'CELL_TYPES %d\n',mesh.totF);
            for i=1:mesh.totF
                fprintf(fid,'9\n');
            end
            fprintf(fid,' \n')
        end
    case 3
        if mesh.cellflag
            fprintf(fid,'CELLS %d %d\n',mesh.totC,mesh.totC*9);
            for i=1:mesh.totC
                fprintf(fid,'8 %d %d %d %d %d %d %d %d\n',mesh.cells.nodes(1,i)-1,mesh.cells.nodes(2,i)-1,mesh.cells.nodes(3,i)-1,mesh.cells.nodes(4,i)-1,mesh.cells.nodes(5,i)-1,mesh.cells.nodes(6,i)-1,mesh.cells.nodes(7,i)-1,mesh.cells.nodes(8,i)-1);
            end
            fprintf(fid,'CELL_TYPES %d\n',mesh.totC);
            for i=1:mesh.totC
                fprintf('12\n');
            end
            fprintf(fid,' \n')
        end
end

%% Pointdatasets
% lines: #nr_datasets*(#nr_points +3)+1
% In this segment of the file, datasets that are associated to the points of the grid can be given. The data can either be of scalar- or vector-type.
% The first line initiates that pointdata will be supplied in the following lines, the "9" simply says how many points per dataset there are (yes, it's redundant).
% We seperate each of the datasets with an empty line. Each of the datasets has two leading lines followed by "9" lines of data.
% The first dataset line specifies if "SCALAR"- or "VECTOR"-data will follow. It also assigns a name to the dataset ("HorizontalSpeed" , "Temperature"). The "FLOAT" specifies the format of the data. "FLOAT" will most likely always be good enough.
% The second line has to do with color tables and "LOOKUP_TABLE default" will most likely be the only setting you will ever need.
% The following "9" lines will either contain per line a scalar-value or a vector-value (consisting of 3 numbers).
% The last line is empty.

%% Celldatasets
% lines: #nr_datasets*(#nr_cells +3)+1
% Exactly the same setup as the point-data, only this data is assigned to cells. 

%% Close file

fclose(fid);

return