# Autogenerated with SMOP 
from smop.core import *
# 

    
@function
def collide3D(Q=None,fold=None,feq=None,Flambda=None,beta=None,dt=None,*args,**kwargs):
    varargin = collide3D.varargin
    nargin = collide3D.nargin

    ##
#        Project: Fluid - structure interaction on deformable surfaces
#         Author: Luca Di Stasio
#    Institution: ETH Zrich
#                 Institute for Building Materials
# Research group: Computational Physics for Engineering Materials
#        Version: 0.1
#  Creation date: May 30th, 2014
#    Last update: June 3rd, 2014
    
    #    Description: 
#          Input: 
#         Output:
    
    ##
    
    for q in arange(1,Q).reshape(-1):
        f[:,q]=multiply((1 - beta[:,1]),fold[:,q]) + multiply(beta[:,1],feq[:,q]) + dot(dt,Flambda[:,q])
    
    return f