# Autogenerated with SMOP 
from smop.core import *
# 

    
@function
def binomialfactor(n=None,k=None,*args,**kwargs):
    varargin = binomialfactor.varargin
    nargin = binomialfactor.nargin

    ##
#        Project: Fluid - structure interaction on deformable surfaces
#         Author: Luca Di Stasio
#    Institution: ETH Zrich
#                 Institute for Building Materials
# Research group: Computational Physics for Engineering Materials
#        Version: 0.1
#  Creation date: May 26th, 2014
#    Last update: May 26th, 2014
    
    #    Description: 
#          Input: 
#         Output:
    
    ##
    
    fac=factorial(n) / (dot(factorial(k),factorial(n - k)))
    return fac