# Autogenerated with SMOP 
from smop.core import *
# 

    
@function
def computegeometricforcing3D(N=None,Q=None,secondChristoffelsymbol=None,scheme=None,*args,**kwargs):
    varargin = computegeometricforcing3D.varargin
    nargin = computegeometricforcing3D.nargin

    ##
#        Project: Fluid - structure interaction on deformable surfaces
#         Author: Luca Di Stasio
#    Institution: ETH Zrich
#                 Institute for Building Materials
# Research group: Computational Physics for Engineering Materials
#        Version: 0.1
#  Creation date: May 30th, 2014
#    Last update: May 30th, 2014
    
    #    Description: 
#          Input: number of lattice points N
#                 number of lattice velocities Q
#         Output:
    
    ##
    
    Fgeom=zeros(N,dot(3,Q))
    xi1=scheme[:,1]
    xi2=scheme[:,2]
    xi3=scheme[:,3]
    Gamma111=secondChristoffelsymbol[:,1]
    Gamma112=secondChristoffelsymbol[:,2]
    Gamma113=secondChristoffelsymbol[:,3]
    Gamma121=secondChristoffelsymbol[:,4]
    Gamma122=secondChristoffelsymbol[:,5]
    Gamma123=secondChristoffelsymbol[:,6]
    Gamma131=secondChristoffelsymbol[:,7]
    Gamma132=secondChristoffelsymbol[:,8]
    Gamma133=secondChristoffelsymbol[:,9]
    Gamma211=secondChristoffelsymbol[:,10]
    Gamma212=secondChristoffelsymbol[:,11]
    Gamma213=secondChristoffelsymbol[:,12]
    Gamma221=secondChristoffelsymbol[:,13]
    Gamma222=secondChristoffelsymbol[:,14]
    Gamma223=secondChristoffelsymbol[:,15]
    Gamma231=secondChristoffelsymbol[:,16]
    Gamma232=secondChristoffelsymbol[:,17]
    Gamma233=secondChristoffelsymbol[:,18]
    Gamma311=secondChristoffelsymbol[:,19]
    Gamma312=secondChristoffelsymbol[:,20]
    Gamma313=secondChristoffelsymbol[:,21]
    Gamma321=secondChristoffelsymbol[:,22]
    Gamma322=secondChristoffelsymbol[:,23]
    Gamma323=secondChristoffelsymbol[:,24]
    Gamma331=secondChristoffelsymbol[:,25]
    Gamma332=secondChristoffelsymbol[:,26]
    Gamma333=secondChristoffelsymbol[:,27]
    for i in arange(1,Q).reshape(-1):
        Fgeom[:,dot(3,(i - 1)) + 1]=- (dot(dot(Gamma111,xi1[i,1]),xi1[i,1]) + dot(dot(Gamma112,xi1[i,1]),xi2[i,1]) + dot(dot(Gamma113,xi1[i,1]),xi3[i,1]) + dot(dot(Gamma121,xi2[i,1]),xi1[i,1]) + dot(dot(Gamma122,xi2[i,1]),xi2[i,1]) + dot(dot(Gamma123,xi2[i,1]),xi3[i,1]) + dot(dot(Gamma131,xi3[i,1]),xi1[i,1]) + dot(dot(Gamma132,xi3[i,1]),xi2[i,1]) + dot(dot(Gamma133,xi3[i,1]),xi3[i,1]))
        Fgeom[:,dot(3,(i - 1)) + 2]=- (dot(dot(Gamma211,xi1[i,1]),xi1[i,1]) + dot(dot(Gamma212,xi1[i,1]),xi2[i,1]) + dot(dot(Gamma213,xi1[i,1]),xi3[i,1]) + dot(dot(Gamma221,xi2[i,1]),xi2[i,1]) + dot(dot(Gamma222,xi2[i,1]),xi2[i,1]) + dot(dot(Gamma223,xi2[i,1]),xi3[i,1]) + dot(dot(Gamma231,xi3[i,1]),xi1[i,1]) + dot(dot(Gamma232,xi3[i,1]),xi2[i,1]) + dot(dot(Gamma233,xi3[i,1]),xi3[i,1]))
        Fgeom[:,dot(3,(i - 1)) + 3]=- (dot(dot(Gamma311,xi1[i,1]),xi1[i,1]) + dot(dot(Gamma312,xi1[i,1]),xi2[i,1]) + dot(dot(Gamma313,xi1[i,1]),xi3[i,1]) + dot(dot(Gamma321,xi2[i,1]),xi1[i,1]) + dot(dot(Gamma322,xi2[i,1]),xi2[i,1]) + dot(dot(Gamma323,xi2[i,1]),xi3[i,1]) + dot(dot(Gamma331,xi3[i,1]),xi1[i,1]) + dot(dot(Gamma332,xi3[i,1]),xi2[i,1]) + dot(dot(Gamma333,xi3[i,1]),xi3[i,1]))
    
    return Fgeom