# Autogenerated with SMOP 
from smop.core import *
# 

    
@function
def computetau3D(N=None,Q=None,feq=None,f=None,rho=None,tau=None,*args,**kwargs):
    varargin = computetau3D.varargin
    nargin = computetau3D.nargin

    ##
#        Project: Fluid - structure interaction on deformable surfaces
#         Author: Luca Di Stasio
#    Institution: ETH Zrich
#                 Institute for Building Materials
# Research group: Computational Physics for Engineering Materials
#        Version: 0.1
#  Creation date: May 30th, 2014
#    Last update: June 24th, 2014
    
    #    Description: 
#          Input: 
#         Output:
    
    ##