# Autogenerated with SMOP 
from smop.core import *
# 

    
@function
def factorial(n=None,*args,**kwargs):
    varargin = factorial.varargin
    nargin = factorial.nargin

    ##
#        Project: Fluid - structure interaction on deformable surfaces
#         Author: Luca Di Stasio
#    Institution: ETH Zrich
#                 Institute for Building Materials
# Research group: Computational Physics for Engineering Materials
#        Version: 0.1
#  Creation date: May 26th, 2014
#    Last update: May 26th, 2014
    
    #    Description: 
#          Input: 
#         Output:
    
    ##
    
    fac=1
    for i in arange(1,n).reshape(-1):
        fac=dot(fac,i)
    
    return fac