# Autogenerated with SMOP 
from smop.core import *
# 

    
@function
def export_csv(mesh=None,filename=None,printflag=None,*args,**kwargs):
    varargin = export_csv.varargin
    nargin = export_csv.nargin

    c=copy(clock)
    basefilename=strcat(cat(num2str(c[1]),'_',num2str(c[2]),'_',num2str(c[3]),'_',filename,'_basedata','.csv'))
    nodesfilename=strcat(cat(num2str(c[1]),'_',num2str(c[2]),'_',num2str(c[3]),'_',filename,'_nodedata','.csv'))
    linesfilename=strcat(cat(num2str(c[1]),'_',num2str(c[2]),'_',num2str(c[3]),'_',filename,'_linedata','.csv'))
    edgesfilename=strcat(cat(num2str(c[1]),'_',num2str(c[2]),'_',num2str(c[3]),'_',filename,'_edgedata','.csv'))
    facesfilename=strcat(cat(num2str(c[1]),'_',num2str(c[2]),'_',num2str(c[3]),'_',filename,'_facedata','.csv'))
    cellsfilename=strcat(cat(num2str(c[1]),'_',num2str(c[2]),'_',num2str(c[3]),'_',filename,'_celldata','.csv'))
    basefid=fopen(basefilename,'w')
    dlmwrite(basefilename,mesh.D,'-append')
    dlmwrite(basefilename,mesh.dim1min,'-append')
    dlmwrite(basefilename,mesh.dim1max,'-append')
    dlmwrite(basefilename,mesh.Ndim1,'-append')
    dlmwrite(basefilename,mesh.dim2min,'-append')
    dlmwrite(basefilename,mesh.dim2max,'-append')
    dlmwrite(basefilename,mesh.Ndim2,'-append')
    dlmwrite(basefilename,mesh.dim3min,'-append')
    dlmwrite(basefilename,mesh.dim3max,'-append')
    dlmwrite(basefilename,mesh.Ndim3,'-append')
    dlmwrite(basefilename,mesh.Nlinesdim1,'-append')
    dlmwrite(basefilename,mesh.Nlinesdim2,'-append')
    dlmwrite(basefilename,mesh.Nlinesdim3,'-append')
    dlmwrite(basefilename,mesh.totN,'-append')
    dlmwrite(basefilename,mesh.totE,'-append')
    dlmwrite(basefilename,mesh.totF,'-append')
    dlmwrite(basefilename,mesh.totC,'-append')
    dlmwrite(basefilename,mesh.edgeflag,'-append')
    dlmwrite(basefilename,mesh.faceflag,'-append')
    dlmwrite(basefilename,mesh.cellflag,'-append')
    fclose(basefid)
    if 1 == mesh.D:
        c=copy(clock)
        if printflag:
            disp(strcat(cat(num2str(c[1]),'_',num2str(c[2]),'_',num2str(c[3]))))
            disp(' ')
            disp('EXPORT MESH TO .csv FILE')
            disp(' ')
            disp('1D mesh')
            fprintf('Start point x0 = %d\\n',mesh.dim1min)
            fprintf('End point xN = %6.2f\\n',mesh.dim1max)
            disp(' ')
            fprintf('Total number of nodes N = %6.2f\\n',mesh.totN)
        if mesh.edgeflag:
            nodefid=fopen(nodesfilename,'w')
            linefid=fopen(linesfilename,'w')
            edgefid=fopen(edgesfilename,'w')
            for i in arange(1,mesh.totN).reshape(-1):
                dlmwrite(nodesfilename,cat(mesh.nodes.id(i),mesh.nodes.meshcoordinates(arange(),i).T,mesh.nodes.edges(arange(),i).T),'-append')
            dlmwrite(linesfilename,mesh.coordlines.dim1free,'-append')
            for i in arange(1,mesh.totE).reshape(-1):
                dlmwrite(filename,cat(mesh.edges.id(i),mesh.edges.centroid(arange(),i).T,mesh.edges.nodes(arange(),i).T),'-append')
            fclose(nodefid)
            fclose(linefid)
            fclose(edgefid)
        else:
            nodefid=fopen(nodesfilename,'w')
            linefid=fopen(linesfilename,'w')
            for i in arange(1,mesh.totN).reshape(-1):
                dlmwrite(nodesfilename,cat(mesh.nodes.id(i),mesh.nodes.meshcoordinates(arange(),i).T),'-append')
            dlmwrite(linesfilename,mesh.coordlines.dim1free,'-append')
            fclose(nodefid)
            fclose(linefid)
        #-----------------------------------------------------------------------------2D--------------------------------------------------------------------------------------------
    else:
        if 2 == mesh.D:
            c=copy(clock)
            if printflag:
                disp(strcat(cat(num2str(c[1]),'_',num2str(c[2]),'_',num2str(c[3]))))
                disp(' ')
                disp('EXPORT MESH TO .csv FILE')
                disp(' ')
                disp('2D mesh')
                fprintf('Lower boundary along the first direction x0 = %d\\n',mesh.dim1min)
                fprintf('Upper boundary along the first direction xN = %6.2f\\n',mesh.dim1max)
                fprintf('Lower boundary along the second direction y0 = %d\\n',mesh.dim2min)
                fprintf('Upper boundary along the second direction yN = %6.2f\\n',mesh.dim2max)
                disp(' ')
                fprintf('Total number of nodes N = %6.2f\\n',mesh.totN)
            if mesh.faceflag and mesh.edgeflag:
                nodefid=fopen(nodesfilename,'w')
                linefid=fopen(linesfilename,'w')
                edgefid=fopen(edgesfilename,'w')
                facefid=fopen(facesfilename,'w')
                for i in arange(1,mesh.totN).reshape(-1):
                    dlmwrite(nodesfilename,cat(mesh.nodes.id(i),mesh.nodes.meshcoordinates(arange(),i).T,mesh.nodes.edges(arange(),i).T,mesh.nodes.faces(arange(),i).T),'-append')
                dlmwrite(linesfilename,mesh.coordlines.dim1free,'-append')
                dlmwrite(linesfilename,mesh.coordlines.dim2free,'-append')
                for i in arange(1,mesh.totE).reshape(-1):
                    dlmwrite(filename,cat(mesh.edges.id(i),mesh.edges.centroid(arange(),i).T,mesh.edges.nodes(arange(),i).T,mesh.edges.faces(arange(),i).T),'-append')
                for i in arange(1,mesh.totF).reshape(-1):
                    dlmwrite(filename,cat(mesh.faces.id(i),mesh.faces.centroid(arange(),i).T,mesh.faces.nodes(arange(),i).T,mesh.faces.edges(arange(),i).T),'-append')
                fclose(nodefid)
                fclose(linefid)
                fclose(edgefid)
                fclose(facefid)
            else:
                if mesh.edgeflag:
                    nodefid=fopen(nodesfilename,'w')
                    linefid=fopen(linesfilename,'w')
                    edgefid=fopen(edgesfilename,'w')
                    for i in arange(1,mesh.totN).reshape(-1):
                        dlmwrite(nodesfilename,cat(mesh.nodes.id(i),mesh.nodes.meshcoordinates(arange(),i).T,mesh.nodes.edges(arange(),i).T),'-append')
                    dlmwrite(linesfilename,mesh.coordlines.dim1free,'-append')
                    dlmwrite(linesfilename,mesh.coordlines.dim2free,'-append')
                    for i in arange(1,mesh.totE).reshape(-1):
                        dlmwrite(filename,cat(mesh.edges.id(i),mesh.edges.centroid(arange(),i).T,mesh.edges.nodes(arange(),i).T),'-append')
                    fclose(nodefid)
                    fclose(linefid)
                    fclose(edgefid)
                else:
                    nodefid=fopen(nodesfilename,'w')
                    linefid=fopen(linesfilename,'w')
                    for i in arange(1,mesh.totN).reshape(-1):
                        dlmwrite(nodesfilename,cat(mesh.nodes.id(i),mesh.nodes.meshcoordinates(arange(),i).T),'-append')
                    dlmwrite(linesfilename,mesh.coordlines.dim1free,'-append')
                    dlmwrite(linesfilename,mesh.coordlines.dim2free,'-append')
                    fclose(nodefid)
                    fclose(linefid)
            #-----------------------------------------------------------------------------3D--------------------------------------------------------------------------------------------
        else:
            if 3 == mesh.D:
                c=copy(clock)
                if printflag:
                    disp(strcat(cat(num2str(c[1]),'_',num2str(c[2]),'_',num2str(c[3]))))
                    disp(' ')
                    disp('EXPORT MESH TO .csv FILE')
                    disp(' ')
                    disp('3D mesh')
                    disp(' ')
                    fprintf('Lower boundary along the first direction x0 = %d\\n',mesh.dim1min)
                    fprintf('Upper boundary along the first direction xN = %6.2f\\n',mesh.dim1max)
                    fprintf('Lower boundary along the second direction y0 = %d\\n',mesh.dim2min)
                    fprintf('Upper boundary along the second direction yN = %6.2f\\n',mesh.dim2max)
                    fprintf('Lower boundary along the second direction z0 = %d\\n',mesh.dim3min)
                    fprintf('Upper boundary along the second direction zN = %6.2f\\n',mesh.dim3max)
                    disp(' ')
                    fprintf('Total number of nodes N = %6.2f\\n',mesh.totN)
                if mesh.cellflag and mesh.faceflag and mesh.edgeflag:
                    nodefid=fopen(nodesfilename,'w')
                    linefid=fopen(linesfilename,'w')
                    edgefid=fopen(edgesfilename,'w')
                    facefid=fopen(facesfilename,'w')
                    cellfid=fopen(cellsfilename,'w')
                    for i in arange(1,mesh.totN).reshape(-1):
                        dlmwrite(nodesfilename,cat(mesh.nodes.id(i),mesh.nodes.meshcoordinates(arange(),i).T,mesh.nodes.edges(arange(),i).T,mesh.nodes.faces(arange(),i).T,mesh.nodes.cells(arange(),i).T),'-append')
                    dlmwrite(linesfilename,mesh.coordlines.dim1free,'-append')
                    dlmwrite(linesfilename,mesh.coordlines.dim2free,'-append')
                    dlmwrite(linesfilename,mesh.coordlines.dim3free,'-append')
                    for i in arange(1,mesh.totE).reshape(-1):
                        dlmwrite(filename,cat(mesh.edges.id(i),mesh.edges.centroid(arange(),i).T,mesh.edges.nodes(arange(),i).T,mesh.edges.faces(arange(),i).T,mesh.edges.cells(arange(),i).T),'-append')
                    for i in arange(1,mesh.totF).reshape(-1):
                        dlmwrite(filename,cat(mesh.faces.id(i),mesh.faces.centroid(arange(),i).T,mesh.faces.nodes(arange(),i).T,mesh.faces.edges(arange(),i).T,mesh.faces.cells(arange(),i).T),'-append')
                    for i in arange(1,mesh.totC).reshape(-1):
                        dlmwrite(filename,cat(mesh.cells.id(i),mesh.cells.centroid(arange(),i).T,mesh.cells.nodes(arange(),i).T,mesh.cells.edges(arange(),i).T,mesh.cells.faces(arange(),i).T),'-append')
                    fclose(nodefid)
                    fclose(linefid)
                    fclose(edgefid)
                    fclose(facefid)
                    fclose(cellfid)
                else:
                    if mesh.faceflag and mesh.edgeflag:
                        nodefid=fopen(nodesfilename,'w')
                        linefid=fopen(linesfilename,'w')
                        edgefid=fopen(edgesfilename,'w')
                        facefid=fopen(facesfilename,'w')
                        for i in arange(1,mesh.totN).reshape(-1):
                            dlmwrite(nodesfilename,cat(mesh.nodes.id(i),mesh.nodes.meshcoordinates(arange(),i).T,mesh.nodes.edges(arange(),i).T,mesh.nodes.faces(arange(),i).T),'-append')
                        dlmwrite(linesfilename,mesh.coordlines.dim1free,'-append')
                        dlmwrite(linesfilename,mesh.coordlines.dim2free,'-append')
                        dlmwrite(linesfilename,mesh.coordlines.dim3free,'-append')
                        for i in arange(1,mesh.totE).reshape(-1):
                            dlmwrite(filename,cat(mesh.edges.id(i),mesh.edges.centroid(arange(),i).T,mesh.edges.nodes(arange(),i).T,mesh.edges.faces(arange(),i).T),'-append')
                        for i in arange(1,mesh.totF).reshape(-1):
                            dlmwrite(filename,cat(mesh.faces.id(i),mesh.faces.centroid(arange(),i).T,mesh.faces.nodes(arange(),i).T,mesh.faces.edges(arange(),i).T),'-append')
                        fclose(nodefid)
                        fclose(linefid)
                        fclose(edgefid)
                        fclose(facefid)
                    else:
                        if mesh.edgeflag:
                            nodefid=fopen(nodesfilename,'w')
                            linefid=fopen(linesfilename,'w')
                            edgefid=fopen(edgesfilename,'w')
                            for i in arange(1,mesh.totN).reshape(-1):
                                dlmwrite(nodesfilename,cat(mesh.nodes.id(i),mesh.nodes.meshcoordinates(arange(),i).T,mesh.nodes.edges(arange(),i).T),'-append')
                            dlmwrite(linesfilename,mesh.coordlines.dim1free,'-append')
                            dlmwrite(linesfilename,mesh.coordlines.dim2free,'-append')
                            dlmwrite(linesfilename,mesh.coordlines.dim3free,'-append')
                            for i in arange(1,mesh.totE).reshape(-1):
                                dlmwrite(filename,cat(mesh.edges.id(i),mesh.edges.centroid(arange(),i).T,mesh.edges.nodes(arange(),i).T),'-append')
                            fclose(nodefid)
                            fclose(linefid)
                            fclose(edgefid)
                        else:
                            nodefid=fopen(nodesfilename,'w')
                            linefid=fopen(linesfilename,'w')
                            fclose(nodefid)
                            fclose(linefid)
                            for i in arange(1,mesh.totN).reshape(-1):
                                dlmwrite(nodesfilename,cat(mesh.nodes.id(i),mesh.nodes.meshcoordinates(arange(),i).T),'-append')
                            dlmwrite(linesfilename,mesh.coordlines.dim1free,'-append')
                            dlmwrite(linesfilename,mesh.coordlines.dim2free,'-append')
                            dlmwrite(linesfilename,mesh.coordlines.dim3free,'-append')
                            fclose(nodefid)
                            fclose(linefid)
    
    return