# Autogenerated with SMOP 
from smop.core import *
# 

    
@function
def savemeshtocsv(date=None,outfilename=None,latticefolder=None,meshfolder=None,N=None,Nx=None,Ny=None,Nz=None,lattice=None,*args,**kwargs):
    varargin = savemeshtocsv.varargin
    nargin = savemeshtocsv.nargin

    ##
#        Project: Fluid - structure interaction on deformable surfaces
#         Author: Luca Di Stasio
#    Institution: ETH Zrich
#                 Institute for Building Materials
# Research group: Computational Physics for Engineering Materials
#        Version: 0.1
#  Creation date: July 29th, 2014
#    Last update: July 29th, 2014
    
    #    Description: 
#          Input: 
#         Output:
    
    ##
    
    baseoutfilename=strcat(outfilename,'_compdomain')
    flags=zeros(37,1)
    flags[1]=1
    savetovtk(date,0,0,baseoutfilename,latticefolder,meshfolder,flags,N,Nx,Ny,Nz,lattice,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0)
    baseoutfilename=strcat(outfilename,'_physdomain')
    flags[1]=0
    flags[2]=1
    savetovtk(date,0,0,baseoutfilename,latticefolder,meshfolder,flags,N,Nx,Ny,Nz,lattice,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0)
    return