%Function for simple BGK collision of populations with quasiequilibria with
% a limiter applied if necessary
function populations = LBMCollide(oldpopulations,popequilibriums,beta, ...
alpha,nx,Limiter,limiterSites)
unlimitedSites = setdiff(1:nx,limiterSites);
populations(:,unlimitedSites) = oldpopulations(:,unlimitedSites) ...
+ beta.*(ones(3,1)*alpha(unlimitedSites)) ...
.*( popequilibriums(:,unlimitedSites) ...
- oldpopulations(:,unlimitedSites) );
if (Limiter == 1)
Sf = LBMEvaluateS(oldpopulations(:,(limiterSites - 1): ...
(limiterSites + 1)),popequilibriums(:,(limiterSites - 1): ...
(limiterSites + 1)),zeros(1,3));
Sfeq = LBMEvaluateS(popequilibriums(:,(limiterSites - 1): ...
(limiterSites + 1)),popequilibriums(:,(limiterSites - 1): ...
(limiterSites + 1)),zeros(1,3));
dS = Sfeq - Sf;
Smed = median(dS);
coeff = sqrt(Smed/dS(2));
populations(:,limiterSites) = popequilibriums(:,limiterSites) ...
+ coeff.*(oldpopulations(:,limiterSites) ...
- popequilibriums(:,limiterSites));
end