% A function to evaluate the entropy.
function S = LBMEvaluateS(populations,popequilibriums,alpha)
alphapop = populations + (ones(3,1)*alpha).*(popequilibriums ...
- populations);
S = -alphapop(1,:).*log(alphapop(1,:)) ...
- alphapop(2,:).*log(alphapop(2,:)./4) ...
- alphapop(3,:).*log(alphapop(3,:)); %eq-2.5