function lattice = stream_lattice(lattice)

    % 1
	lattice_distribution = lattice{1};
	size_lattice = size(lattice_distribution(:, :, 1));
	number_lines_lattice = size_lattice(1);
	number_columns_lattice = size_lattice(2);

    % 2
    lattice_distribution(:,:,1) = [lattice_distribution(:,1:2,1) ...
    lattice_distribution(:,2:number_columns_lattice-1,1)];
    lattice_distribution(:,:,2) = [lattice_distribution(1:2,:,2); ...
    lattice_distribution(2:number_lines_lattice-1,:,2)];
    lattice_distribution(:,:,3) = [lattice_distribution(:,2:number_columns_lattice-1,3) ...
    lattice_distribution(:,number_columns_lattice-1:number_columns_lattice,3)];
    lattice_distribution(:,:,4) = [lattice_distribution(2:number_lines_lattice-1,:,4); ... 
    lattice_distribution(number_lines_lattice-1:number_lines_lattice,:,4)];
    lattice_distribution(:,:,5) = [lattice_distribution(:,1:2,5) ...
    lattice_distribution(:,2:number_columns_lattice-1,5)];
    lattice_distribution(:,:,5) = [lattice_distribution(1:2,:,5); ... 
    lattice_distribution(2:number_lines_lattice-1,:,5)];
    lattice_distribution(:,:,6) = [lattice_distribution(:,2:number_columns_lattice-1,6) ...
    lattice_distribution(:,number_columns_lattice-1:number_columns_lattice,6)];
    lattice_distribution(:,:,6) = [lattice_distribution(1:2,:,6); ... 
    lattice_distribution(2:number_lines_lattice-1,:,6)];
    lattice_distribution(:,:,7) = [lattice_distribution(:,2:number_columns_lattice-1,7) ...
    lattice_distribution(:,number_columns_lattice-1:number_columns_lattice,7)];
    lattice_distribution(:,:,7) = [lattice_distribution(2:number_lines_lattice-1,:,7); ... 
    lattice_distribution(number_lines_lattice-1:number_lines_lattice,:,7)];
    lattice_distribution(:,:,8) = [lattice_distribution(:,1:2,8) ...
    lattice_distribution(:,2:number_columns_lattice-1,8)];
    lattice_distribution(:,:,8) = [lattice_distribution(2:number_lines_lattice-1,:,8); ... 
    lattice_distribution(number_lines_lattice-1:number_lines_lattice,:,8)];

    %% 3 - Recalculating velocities
    velocity_vectors_x = [1 0 -1  0 1 -1 -1  1 0];
	velocity_vectors_y = [0 1  0 -1 1  1 -1 -1 0];
    density_total = sum(lattice_distribution,3);
    lattice_velocity_x = lattice{2};
    lattice_velocity_x = (velocity_vectors_x(1).*lattice_distribution(:,:,1) + ... 
    velocity_vectors_x(2).*lattice_distribution(:,:,2) + ... 
    velocity_vectors_x(3).*lattice_distribution(:,:,3) + ... 
    velocity_vectors_x(4).*lattice_distribution(:,:,4) + ... 
    velocity_vectors_x(5).*lattice_distribution(:,:,5) + ... 
    velocity_vectors_x(6).*lattice_distribution(:,:,6) + ... 
    velocity_vectors_x(7).*lattice_distribution(:,:,7) + ... 
    velocity_vectors_x(8).*lattice_distribution(:,:,8))./density_total ;
    lattice_velocity_y = lattice{3};
    lattice_velocity_y = (velocity_vectors_y(1).*lattice_distribution(:,:,1) + ... 
    velocity_vectors_y(2).*lattice_distribution(:,:,2) + ... 
    velocity_vectors_y(3).*lattice_distribution(:,:,3) + ... 
    velocity_vectors_y(4).*lattice_distribution(:,:,4) + ... 
    velocity_vectors_y(5).*lattice_distribution(:,:,5) + ... 
    velocity_vectors_y(6).*lattice_distribution(:,:,6) + ... 
    velocity_vectors_y(7).*lattice_distribution(:,:,7) + ... 
    velocity_vectors_y(8).*lattice_distribution(:,:,8))./density_total ;

    %% 4
    lattice{1} = lattice_distribution;
    lattice{2} = lattice_velocity_x;
    lattice{3} = lattice_velocity_y;