# Autogenerated with SMOP 
from smop.core import *
# 

    
@function
def get_inputpath(*args,**kwargs):
    varargin = get_inputpath.varargin
    nargin = get_inputpath.nargin

    ##
#        Project: Fluid - structure interaction on deformable surfaces
#         Author: Luca Di Stasio
#    Institution: ETH Zrich
#                 Institute for Building Materials
# Research group: Computational Physics for Engineering Materials
#        Version: 0.1
#  Creation date: July 9th, 2014
#    Last update: July 9th, 2014
    
    #    Description: 
#          Input: 
#         Output:
    
    ##
    
    basepath='/home/lucadistasio/Documents/ETH/Research_material/Numerics'
    folder='Numerical_experiments'
    configname='config'
    fprintf('The basepath is set to %s. Do you want to change it? (yes/no) ',basepath)
    basepathchange=input_('','s')
    fprintf('\\n')
    if isempty(basepathchange):
        basepathchange='no'
    
    if strcmp(basepathchange,'yes') or strcmp(basepathchange,'Yes') or strcmp(basepathchange,'YES') or strcmp(basepathchange,'yep') or strcmp(basepathchange,'Y') or strcmp(basepathchange,'y') or strcmp(basepathchange,'ye') or strcmp(basepathchange,'yeah') or strcmp(basepathchange,'ok') or strcmp(basepathchange,'OK') or strcmp(basepathchange,'Ok'):
        fprintf('Input the new basepath: ')
        basepath=input_('','s')
        fprintf('\\n')
    
    fprintf('The current folder is %s. Do you want to change it? (yes/no) ',folder)
    folderchange=input_('','s')
    fprintf('\\n')
    if isempty(folderchange):
        folderchange='no'
    
    if strcmp(folderchange,'yes') or strcmp(folderchange,'Yes') or strcmp(folderchange,'YES') or strcmp(folderchange,'yep') or strcmp(folderchange,'Y') or strcmp(folderchange,'y') or strcmp(folderchange,'ye') or strcmp(folderchange,'yeah') or strcmp(folderchange,'ok') or strcmp(folderchange,'OK') or strcmp(folderchange,'Ok'):
        fprintf('Input the new folder: ')
        folder=input_('','s')
        fprintf('\\n')
    
    fprintf('The current configuration file is %s. Do you want to change it? (yes/no) ',configname)
    confignamechange=input_('','s')
    fprintf('\\n')
    if isempty(confignamechange):
        confignamechange='no'
    
    if strcmp(confignamechange,'yes') or strcmp(confignamechange,'Yes') or strcmp(confignamechange,'YES') or strcmp(confignamechange,'yep') or strcmp(confignamechange,'Y') or strcmp(confignamechange,'y') or strcmp(confignamechange,'ye') or strcmp(confignamechange,'yeah') or strcmp(confignamechange,'ok') or strcmp(confignamechange,'OK') or strcmp(confignamechange,'Ok'):
        fprintf('Input the new configuration file: ')
        configname=input_('','s')
        fprintf('\\n')
    
    return basepath,folder,configname