%PsiFun Function for intial based  functions.
%   ref:https://github.com/Jiaqi-knight/NonlinearWaveguideCoding
%   Email:Jiaqi_Wang@sjtu.edu.cn
%Copyright 2020, SJTU.



function [Ad]= RKFUN(Geo_b,RK_b,Out,OutRK,Wave,or_n,or_r) 

tic
disp('RK Algorithm..Begin...')

%% RK4,a,ab,b-James-3.37
%a
Y_a_0=Out.Y0_a(:,:,end,:);
Ad.Y_a(:,:,length(or_n),:)=Y_a_0;
for k=1:length(or_n)-1
    k_1= - multiprod(multiprod(Y_a_0,Out.N_a(:,:,length(or_n)-k+1,:),[1,2]),Y_a_0,[1,2])- Out.M_a(:,:,length(or_n)-k+1,:) - multiprod(Y_a_0,Out.H_a(:,:,length(or_n)-k+1,:),[1,2]) - multiprod(Out.G_a(:,:,length(or_n)-k+1,:),Y_a_0,[1,2]);
    Y_1= Y_a_0-k_1*(Geo_b.s(length(or_n)-k+1)-RK_b.s(length(or_r)-k+1));
    %max(max(max(k_1)))
    k_2= - multiprod(multiprod(Y_1,OutRK.N_a(:,:,length(or_r)-k+1,:),[1,2]),Y_1,[1,2])-OutRK.M_a(:,:,length(or_r)-k+1,:) -  multiprod(Y_1,OutRK.H_a(:,:,length(or_r)-k+1,:),[1,2]) - multiprod(OutRK.G_a(:,:,length(or_r)-k+1,:),Y_1,[1,2]);
    Y_2= Y_a_0-k_2*(Geo_b.s(length(or_n)-k+1)-RK_b.s(length(or_r)-k+1));
    %max(max(max(k_2)))
    k_3= - multiprod(multiprod(Y_2,OutRK.N_a(:,:,length(or_r)-k+1,:),[1,2]),Y_2,[1,2])-OutRK.M_a(:,:,length(or_r)-k+1,:) - multiprod(Y_2,OutRK.H_a(:,:,length(or_r)-k+1,:),[1,2]) - multiprod(OutRK.G_a(:,:,length(or_r)-k+1,:),Y_2,[1,2]);
    Y_3= Y_a_0-k_3*(Geo_b.s(length(or_n)-k+1)-Geo_b.s(length(or_n)-k));
    %max(max(max(k_3)))
    k_4= - multiprod(multiprod(Y_3,Out.N_a(:,:,length(or_n)-k,:),[1,2]),Y_3,[1,2])-Out.M_a(:,:,length(or_n)-k,:) - multiprod(Y_3,Out.H_a(:,:,length(or_n)-k,:),[1,2]) - multiprod(Out.G_a(:,:,length(or_n)-k,:),Y_3,[1,2]);
    %max(max(max(k_4)))
    Y_a_0= Y_a_0 - (1/6)*(k_1+2*k_2+2*k_3+k_4)*(Geo_b.s(length(or_n)-k+1)-Geo_b.s(length(or_n)-k));
    Ad.Y_a(:,:,length(or_n)-k,:)=Y_a_0;
    Ad.Y_a1(:,:,length(or_n)-k,:)=1/2*(Y_1+Y_2);
end
%b
Y_b_0=Out.Y0_b(:,:,end,:);
Ad.Y_b(:,:,length(or_n),:)=Y_b_0;
for k=1:length(or_n)-1
    k_1= - multiprod(multiprod(Y_b_0,Out.N_b(:,:,length(or_n)-k+1,:),[1,2]),Y_b_0,[1,2])- Out.M_b(:,:,length(or_n)-k+1,:) - multiprod(Y_b_0,Out.H_b(:,:,length(or_n)-k+1,:),[1,2]) - multiprod(Out.G_b(:,:,length(or_n)-k+1,:),Y_b_0,[1,2]);
    Y_1= Y_b_0-k_1*(Geo_b.s(length(or_n)-k+1)-RK_b.s(length(or_r)-k+1));
    %max(max(max(k_1)))
    k_2= - multiprod(multiprod(Y_1,OutRK.N_b(:,:,length(or_r)-k+1,:),[1,2]),Y_1,[1,2])-OutRK.M_b(:,:,length(or_r)-k+1,:) -  multiprod(Y_1,OutRK.H_b(:,:,length(or_r)-k+1,:),[1,2]) - multiprod(OutRK.G_b(:,:,length(or_r)-k+1,:),Y_1,[1,2]);
    Y_2= Y_b_0-k_2*(Geo_b.s(length(or_n)-k+1)-RK_b.s(length(or_r)-k+1));
    %max(max(max(k_2)))
    k_3= - multiprod(multiprod(Y_2,OutRK.N_b(:,:,length(or_r)-k+1,:),[1,2]),Y_2,[1,2])-OutRK.M_b(:,:,length(or_r)-k+1,:) - multiprod(Y_2,OutRK.H_b(:,:,length(or_r)-k+1,:),[1,2]) - multiprod(OutRK.G_b(:,:,length(or_r)-k+1,:),Y_2,[1,2]);
    Y_3= Y_b_0-k_3*(Geo_b.s(length(or_n)-k+1)-Geo_b.s(length(or_n)-k));
    %max(max(max(k_3)))
    k_4= - multiprod(multiprod(Y_3,Out.N_b(:,:,length(or_n)-k,:),[1,2]),Y_3,[1,2])-Out.M_b(:,:,length(or_n)-k,:) - multiprod(Y_3,Out.H_b(:,:,length(or_n)-k,:),[1,2]) - multiprod(Out.G_b(:,:,length(or_n)-k,:),Y_3,[1,2]);
    %max(max(max(k_4)))
    Y_b_0= Y_b_0 - (1/6)*(k_1+2*k_2+2*k_3+k_4)*(Geo_b.s(length(or_n)-k+1)-Geo_b.s(length(or_n)-k));
    Ad.Y_b(:,:,length(or_n)-k,:)=Y_b_0;
    Ad.Y_b1(:,:,length(or_n)-k,:)=1/2*(Y_1+Y_2);
end
%a_b
Y_a_b_0=Out.Y0_a_b(:,:,end,:,:);
Ad.Y_a_b(:,:,length(or_n),:,:)=Y_a_b_0;
for k=1:length(or_n)-1
    k_1= - multiprod(multiprod(Y_a_b_0,Out.N_a_b(:,:,length(or_n)-k+1,:,:),[1,2]),Y_a_b_0,[1,2])- Out.M_a_b(:,:,length(or_n)-k+1,:,:) - multiprod(Y_a_b_0,Out.H_a_b(:,:,length(or_n)-k+1,:,:),[1,2]) - multiprod(Out.G_a_b(:,:,length(or_n)-k+1,:,:),Y_a_b_0,[1,2]);
    Y_1= Y_a_b_0-k_1*(Geo_b.s(length(or_n)-k+1)-RK_b.s(length(or_r)-k+1));
    %max(max(max(k_1)))
    k_2= - multiprod(multiprod(Y_1,OutRK.N_a_b(:,:,length(or_r)-k+1,:,:),[1,2]),Y_1,[1,2])-OutRK.M_a_b(:,:,length(or_r)-k+1,:,:) -  multiprod(Y_1,OutRK.H_a_b(:,:,length(or_r)-k+1,:,:),[1,2]) - multiprod(OutRK.G_a_b(:,:,length(or_r)-k+1,:,:),Y_1,[1,2]);
    Y_2= Y_a_b_0-k_2*(Geo_b.s(length(or_n)-k+1)-RK_b.s(length(or_r)-k+1));
    %max(max(max(k_2)))
    k_3= - multiprod(multiprod(Y_2,OutRK.N_a_b(:,:,length(or_r)-k+1,:,:),[1,2]),Y_2,[1,2])-OutRK.M_a_b(:,:,length(or_r)-k+1,:,:) - multiprod(Y_2,OutRK.H_a_b(:,:,length(or_r)-k+1,:,:),[1,2]) - multiprod(OutRK.G_a_b(:,:,length(or_r)-k+1,:,:),Y_2,[1,2]);
    Y_3= Y_a_b_0-k_3*(Geo_b.s(length(or_n)-k+1)-Geo_b.s(length(or_n)-k));
    %max(max(max(k_3)))
    k_4= - multiprod(multiprod(Y_3,Out.N_a_b(:,:,length(or_n)-k,:,:),[1,2]),Y_3,[1,2])-Out.M_a_b(:,:,length(or_n)-k,:,:) - multiprod(Y_3,Out.H_a_b(:,:,length(or_n)-k,:,:),[1,2]) - multiprod(Out.G_a_b(:,:,length(or_n)-k,:,:),Y_3,[1,2]);
    %max(max(max(k_4)))
    Y_a_b_0= Y_a_b_0 - (1/6)*(k_1+2*k_2+2*k_3+k_4)*(Geo_b.s(length(or_n)-k+1)-Geo_b.s(length(or_n)-k));
    Ad.Y_a_b(:,:,length(or_n)-k,:,:)=Y_a_b_0;
    Ad.Y_a_b_1(:,:,length(or_n)-k,:,:)=1/2*(Y_1+Y_2);
end

%vertification
% max(max(max(Ad.Y_a(:,:,1,:)-Ad.Y_a(:,:,end,:))))
% max(max(max(Ad.Y_b(:,:,1,:)-Ad.Y_b(:,:,end,:))))
% max(max(max(Ad.Y_a_b(:,:,1,:)-Ad.Y_a_b(:,:,end,:))))
% max(max(Ad.Y_a_b(:,:,2,5,3)-Ad.Y_a(:,:,2,1)))
% max(max(Ad.Y_a_b(:,:,2,5,3)-Ad.Y_b(:,:,2,4)))

% YY,James-3.38

Out.Y_a=     permute(bsxfun(@times,Ad.Y_a,reshape(ones(size(Wave.b)),1,1,1,1,length(Wave.b))),[1,2,6,3,5,4]);
Out.Y_a_b=   permute(Ad.Y_a_b,[1,2,6,3,4,5]);
Out.Y_b  =   permute(bsxfun(@times,Ad.Y_b,reshape(ones(size(Wave.a)),1,1,1,1,length(Wave.a))),[6,1,2,3,4,5]);
Out.NY_a=   permute(bsxfun(@times,multiprod(Ad.Y_a,Out.N_a,[1,2]),reshape(ones(size(Wave.b)),1,1,1,1,length(Wave.b))),[1,2,6,3,5,4]);
Out.NY_a_b= permute(multiprod(Ad.Y_a_b,Out.N_a_b,[1,2]),[1,2,6,3,4,5]);%5D->6D
Out.NY_b=   permute(bsxfun(@times,multiprod(Ad.Y_b,Out.N_b,[1,2]),reshape(ones(size(Wave.a)),1,1,1,1,length(Wave.a))),[6,1,2,3,4,5]);
Out.H3_a_b= permute(Out.H_a_b,[1,2,6,3,4,5]);
Out.H3_b=   permute(bsxfun(@times,Out.H_b,reshape(ones(size(Wave.a)),1,1,1,1,length(Wave.a))),[6,1,2,3,4,5]);
Out.G3_a=   permute(bsxfun(@times,Out.G_a,reshape(ones(size(Wave.b)),1,1,1,1,length(Wave.b))),[1,2,6,3,5,4]);

OutRK.Y_a1=    permute(bsxfun(@times,Ad.Y_a1,reshape(ones(size(Wave.b)),1,1,1,1,length(Wave.b))),[1,2,6,3,5,4]);
OutRK.Y_a_b_1= permute(Ad.Y_a_b_1,[1,2,6,3,4,5]);
OutRK.Y_b1  =  permute(bsxfun(@times,Ad.Y_b1,reshape(ones(size(Wave.a)),1,1,1,1,length(Wave.a))),[6,1,2,3,4,5]);
OutRK.NY_a=    permute(bsxfun(@times,multiprod(Ad.Y_a1,OutRK.N_a,[1,2]),reshape(ones(size(Wave.b)),1,1,1,1,length(Wave.b))),[1,2,6,3,5,4]);
OutRK.NY_a_b=  permute(multiprod(Ad.Y_a_b_1,OutRK.N_a_b,[1,2]),[1,2,6,3,4,5]);%5D->6D
OutRK.NY_b=    permute(bsxfun(@times,multiprod(Ad.Y_b1,OutRK.N_b,[1,2]),reshape(ones(size(Wave.a)),1,1,1,1,length(Wave.a))),[6,1,2,3,4,5]);
OutRK.H3_a_b=  permute(OutRK.H_a_b,[1,2,6,3,4,5]);
OutRK.H3_b=    permute(bsxfun(@times,OutRK.H_b,reshape(ones(size(Wave.a)),1,1,1,1,length(Wave.a))),[6,1,2,3,4,5]);
OutRK.G3_a=    permute(bsxfun(@times,OutRK.G_a,reshape(ones(size(Wave.b)),1,1,1,1,length(Wave.b))),[1,2,6,3,5,4]);
%a
clear YY_a_0
YY_a_0=Out.YY0_ab(:,:,:,end,:,:);
Ad.YY_ab(:,:,:,length(or_n),:,:)=YY_a_0;
for k=1:length(or_n)-1
    k_1= - multiprod(multiprod(YY_a_0,           Out.NY_a_b(:,:,:,length(or_n)-k+1,:,:),[1,2]), Out.I_b,[2,3])...
        - multiprod(multiprod(YY_a_0,           Out.I_a_b,[1,2]),  Out.NY_b(:,:,:,length(or_n)-k+1,:,:),[2,3])...
        - multiprod(Out.NY_a(:,:,:,length(or_n)-k+1,:,:),...
        multiprod(multiprod(YY_a_0, Out.I_a_b,[1,2]),  Out.I_b,[2,3]),...
        [1,2])...
        - multiprod(Out.Y_a(:,:,:,length(or_n)-k+1,:,:),...
        multiprod(multiprod(Out.C(:,:,:,length(or_n)-k+1,:,:),  Out.Y_a_b(:,:,:,length(or_n)-k+1,:,:),[1,2]),  Out.I_b,[2,3]),...
        [1,2])...
        + multiprod(multiprod(Out.A(:,:,:,length(or_n)-k+1,:,:),            Out.Y_a_b(:,:,:,length(or_n)-k+1,:,:),[1,2]),  Out.Y_b(:,:,:,length(or_n)-k+1,:,:),[2,3])...
        + multiprod(multiprod(Out.B(:,:,:,length(or_n)-k+1,:,:),            Out.I_a_b,[1,2]),  Out.I_b,[2,3])...
        - multiprod(multiprod(YY_a_0,           Out.H3_a_b(:,:,:,length(or_n)-k+1,:,:),[1,2]), Out.I_b,[2,3])...
        - multiprod(multiprod(YY_a_0,           Out.I_a_b,[1,2]),  Out.H3_b(:,:,:,length(or_n)-k+1,:,:),[2,3])...
        - multiprod(Out.G3_a(:,:,:,length(or_n)-k+1,:,:),...
        multiprod(multiprod(YY_a_0, Out.I_a_b,[1,2]),  Out.I_b,[2,3]),...
        [1,2])...
        - multiprod(Out.Y_a(:,:,:,length(or_n)-k+1,:,:),...
        multiprod(multiprod(Out.D(:,:,:,length(or_n)-k+1,:,:), Out.Y_a_b(:,:,:,length(or_n)-k+1,:,:),[1,2]),  Out.Y_b(:,:,:,length(or_n)-k+1,:,:),[2,3]),...
        [1,2])...
        + multiprod(multiprod(Out.E(:,:,:,length(or_n)-k+1,:,:),            Out.Y_a_b(:,:,:,length(or_n)-k+1,:,:),[1,2]),  Out.I_b,[2,3]);
    YY_1= YY_a_0-k_1*(Geo_b.s(length(or_n)-k+1)-RK_b.s(length(or_r)-k+1));
    %max(max(max(k_1(:,:,:,1,1,1))))
    k_2= - multiprod(multiprod(YY_1,           OutRK.NY_a_b(:,:,:,length(or_r)-k+1,:,:),[1,2]), Out.I_b,[2,3])...
        - multiprod(multiprod(YY_1,           Out.I_a_b,[1,2]),  OutRK.NY_b(:,:,:,length(or_r)-k+1,:,:),[2,3])...
        - multiprod(OutRK.NY_a(:,:,:,length(or_r)-k+1,:,:),...
        multiprod(multiprod(YY_1, Out.I_a_b,[1,2]),  Out.I_b,[2,3]),...
        [1,2])...
        - multiprod(OutRK.Y_a1(:,:,:,length(or_r)-k+1,:,:),...
        multiprod(multiprod(OutRK.C(:,:,:,length(or_r)-k+1,:,:),  OutRK.Y_a_b_1(:,:,:,length(or_r)-k+1,:,:),[1,2]),  Out.I_b,[2,3]),...
        [1,2])...
        + multiprod(multiprod(OutRK.A(:,:,:,length(or_r)-k+1,:,:),            OutRK.Y_a_b_1(:,:,:,length(or_r)-k+1,:,:),[1,2]),  OutRK.Y_b1(:,:,:,length(or_r)-k+1,:,:),[2,3])...
        + multiprod(multiprod(OutRK.B(:,:,:,length(or_r)-k+1,:,:),            Out.I_a_b,[1,2]),  Out.I_b,[2,3])...
        - multiprod(multiprod(YY_1,           OutRK.H3_a_b(:,:,:,length(or_r)-k+1,:,:),[1,2]), Out.I_b,[2,3])...
        - multiprod(multiprod(YY_1,           Out.I_a_b,[1,2]),  OutRK.H3_b(:,:,:,length(or_r)-k+1,:,:),[2,3])...
        - multiprod(OutRK.G3_a(:,:,:,length(or_r)-k+1,:,:),...
        multiprod(multiprod(YY_1, Out.I_a_b,[1,2]),  Out.I_b,[2,3]),...
        [1,2])...
        - multiprod(OutRK.Y_a1(:,:,:,length(or_r)-k+1,:,:),...
        multiprod(multiprod(OutRK.D(:,:,:,length(or_r)-k+1,:,:),OutRK.Y_a_b_1(:,:,:,length(or_r)-k+1,:,:),[1,2]),  OutRK.Y_b1(:,:,:,length(or_r)-k+1,:,:),[2,3]),...
        [1,2])...
        + multiprod(multiprod(OutRK.E(:,:,:,length(or_r)-k+1,:,:),          OutRK.Y_a_b_1(:,:,:,length(or_r)-k+1,:,:),[1,2]),  Out.I_b,[2,3]);
    YY_2= YY_a_0-k_2*(Geo_b.s(length(or_n)-k+1)-RK_b.s(length(or_r)-k+1));
    %max(max(max(k_2(:,:,:,1,1,1))))
    k_3= - multiprod(multiprod(YY_2,           OutRK.NY_a_b(:,:,:,length(or_r)-k+1,:,:),[1,2]), Out.I_b,[2,3])...
        - multiprod(multiprod(YY_2,           Out.I_a_b,[1,2]),  OutRK.NY_b(:,:,:,length(or_r)-k+1,:,:),[2,3])...
        - multiprod(OutRK.NY_a(:,:,:,length(or_r)-k+1,:,:),...
        multiprod(multiprod(YY_2, Out.I_a_b,[1,2]),  Out.I_b,[2,3]),...
        [1,2])...
        - multiprod(OutRK.Y_a1(:,:,:,length(or_r)-k+1,:,:),...
        multiprod(multiprod(OutRK.C(:,:,:,length(or_r)-k+1,:,:), OutRK.Y_a_b_1(:,:,:,length(or_r)-k+1,:,:),[1,2]),  Out.I_b,[2,3]),...
        [1,2])...
        + multiprod(multiprod(OutRK.A(:,:,:,length(or_r)-k+1,:,:),          OutRK.Y_a_b_1(:,:,:,length(or_r)-k+1,:,:),[1,2]),  OutRK.Y_b1(:,:,:,length(or_r)-k+1,:,:),[2,3])...
        + multiprod(multiprod(OutRK.B(:,:,:,length(or_r)-k+1,:,:),          Out.I_a_b,[1,2]),  Out.I_b,[2,3])...
        - multiprod(multiprod(YY_2,           OutRK.H3_a_b(:,:,:,length(or_r)-k+1,:,:),[1,2]), Out.I_b,[2,3])...
        - multiprod(multiprod(YY_2,           Out.I_a_b,[1,2]),  OutRK.H3_b(:,:,:,length(or_r)-k+1,:,:),[2,3])...
        - multiprod(OutRK.G3_a(:,:,:,length(or_r)-k+1,:,:),...
        multiprod(multiprod(YY_2, Out.I_a_b,[1,2]),  Out.I_b,[2,3]),...
        [1,2])...
        - multiprod(OutRK.Y_a1(:,:,:,length(or_r)-k+1,:,:),...
        multiprod(multiprod(OutRK.D(:,:,:,length(or_r)-k+1,:,:),OutRK.Y_a_b_1(:,:,:,length(or_r)-k+1,:,:),[1,2]),  OutRK.Y_b1(:,:,:,length(or_r)-k+1,:,:),[2,3]),...
        [1,2])...
        + multiprod(multiprod(OutRK.E(:,:,:,length(or_r)-k+1,:,:),          OutRK.Y_a_b_1(:,:,:,length(or_r)-k+1,:,:),[1,2]),  Out.I_b,[2,3]);
    YY_3= YY_a_0-k_3*(Geo_b.s(length(or_n)-k+1)-Geo_b.s(length(or_n)-k));
    %max(max(max(k_3(:,:,:,1,1,1))));
    k_4= - multiprod(multiprod(YY_3,           Out.NY_a_b(:,:,:,length(or_n)-k,:,:),[1,2]), Out.I_b,[2,3])...
        - multiprod(multiprod(YY_3,           Out.I_a_b,[1,2]),  Out.NY_b(:,:,:,length(or_n)-k,:,:),[2,3])...
        - multiprod(Out.NY_a(:,:,:,length(or_n)-k,:,:),...
        multiprod(multiprod(YY_3, Out.I_a_b,[1,2]),  Out.I_b,[2,3]),...
        [1,2])...
        - multiprod(Out.Y_a(:,:,:,length(or_n)-k,:,:),...
        multiprod(multiprod(Out.C(:,:,:,length(or_n)-k,:,:),Out.Y_a_b(:,:,:,length(or_n)-k,:,:),[1,2]),  Out.I_b,[2,3]),...
        [1,2])...
        + multiprod(multiprod(Out.A(:,:,:,length(or_n)-k,:,:),          Out.Y_a_b(:,:,:,length(or_n)-k,:,:),[1,2]),  Out.Y_b(:,:,:,length(or_n)-k,:,:),[2,3])...
        + multiprod(multiprod(Out.B(:,:,:,length(or_n)-k,:,:),          Out.I_a_b,[1,2]),  Out.I_b,[2,3])...
        - multiprod(multiprod(YY_3,           Out.H3_a_b(:,:,:,length(or_n)-k,:,:),[1,2]), Out.I_b,[2,3])...
        - multiprod(multiprod(YY_3,           Out.I_a_b,[1,2]),  Out.H3_b(:,:,:,length(or_n)-k,:,:),[2,3])...
        - multiprod(Out.G3_a(:,:,:,length(or_n)-k,:,:),...
        multiprod(multiprod(YY_3, Out.I_a_b,[1,2]),  Out.I_b,[2,3]),...
        [1,2])...
        - multiprod(Out.Y_a(:,:,:,length(or_n)-k,:,:),...
        multiprod(multiprod(Out.D(:,:,:,length(or_n)-k,:,:), Out.Y_a_b(:,:,:,length(or_n)-k,:,:),[1,2]),  Out.Y_b(:,:,:,length(or_n)-k,:,:),[2,3]),...
        [1,2])...
        + multiprod(multiprod(Out.E(:,:,:,length(or_n)-k,:,:),          Out.Y_a_b(:,:,:,length(or_n)-k,:,:),[1,2]),  Out.I_b,[2,3]);
    %max(max(max(k_4(:,:,:,1,1,1))));
    
    YY_a_0= YY_a_0 - (1/6)*(k_1+2*k_2+2*k_3+k_4)*(Geo_b.s(length(or_n)-k+1)-Geo_b.s(length(or_n)-k));
    Ad.YY_ab(:,:,:,length(or_n)-k,:,:)=YY_a_0;
    Ad.YY_ab1(:,:,:,length(or_n)-k,:,:)=1/2*(YY_1+YY_2);
end


%vertification
max(max(max(Ad.YY_ab(:,:,:,1,:,:)-Ad.YY_ab(:,:,:,end,:,:))));
max(max(max(Ad.YY_ab(:,:,:,1,5,3))));  %NaN

disp('RK Algorithm..Finish!')
toc

Ad.Y_a(find(isnan(Ad.Y_a)))=0;
Ad.YY_ab(find(isnan(Ad.YY_ab)))=0;
Ad.Y_a_b(find(isnan(Ad.Y_a_b)))=0;
Ad.Y_b(find(isnan(Ad.Y_b)))=0;

end